# Generated by Django 4.1.7 on 2023-04-01 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("splice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.FloatField()),
                ("reference", models.CharField(max_length=100)),
                ("is_completed", models.BooleanField(default=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spent_cash",
                        to="splice.spliceuser",
                    ),
                ),
                (
                    "receipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_cash",
                        to="splice.spliceuser",
                    ),
                ),
            ],
        ),
    ]
