# Generated by Django 4.1.7 on 2023-04-08 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("splice", "0002_payments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="receipient",
            new_name="recepient",
        ),
        migrations.AddField(
            model_name="payments",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payments",
            name="item_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
