# Generated by Django 4.1.7 on 2023-04-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("splice", "0003_rename_receipient_payments_recepient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="item_name",
            new_name="item_id",
        ),
        migrations.AlterField(
            model_name="payments",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payments",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
