# Generated by Django 4.1.7 on 2023-04-15 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("splice", "0004_rename_item_name_payments_item_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userscard",
            name="card_name",
        ),
    ]
