# Generated by Django 4.1.7 on 2023-04-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("splice", "0005_remove_userscard_card_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
