# Generated by Django 4.1.7 on 2023-04-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("splice", "0006_alter_payments_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="spent_cash",
                to="splice.spliceuser",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="recepient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="received_cash",
                to="splice.spliceuser",
            ),
        ),
    ]
