# Generated by Django 4.1.7 on 2023-04-21 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("splice", "0008_alter_payments_initiator_alter_payments_recepient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userscard",
            name="first_four_digits",
        ),
    ]
